[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

[context.production]
  environment = { REACT_APP_TYPE = 'production' }

[context.staging]
  environment = { REACT_APP_TYPE = 'staging' }